[general]
import = [
  "~/.config/alacritty/themes/dracula.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"
